version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true
max_line_length=100

[[analyzers]]
name = "python"
enabled = true
max_line_length=100

  [analyzers.meta]
  runtime_version = "3.x.x"
